# Generated by Django 6.1.1 on 2026-09-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_reference_id_user_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SuperAdmin'), (2, 'SubAdmin'), (3, 'Teacher'), (4, 'Proctor'), (5, 'Student'), (6, 'OrganisationAdmin')], default=5, null=True),
        ),
    ]
