# Generated by Django 6.1.1 on 2026-09-17 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_questionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Total duration of the test in minutes')),
                ('number_of_questions', models.PositiveIntegerField(default=0, help_text='Kept in step with the pattern: the questions its sections add up to')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, help_text='Kept in step with the pattern: the marks the selected questions carry', max_digits=7)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.PositiveIntegerField()),
                ('allow_negative_marking', models.BooleanField(default=False, help_text="Whether a wrong answer costs the question's own negative mark")),
                ('easy_questions', models.PositiveIntegerField(default=0, help_text='How many of the questions must be Easy')),
                ('medium_questions', models.PositiveIntegerField(default=0, help_text='How many of the questions must be Medium')),
                ('hard_questions', models.PositiveIntegerField(default=0, help_text='How many of the questions must be Hard')),
                ('selection_type', models.CharField(choices=[('Manual', 'Manual'), ('Random', 'Random')], default='Random', help_text='Manual: the admin picks the questions. Random: picked from the question bank.', max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.assessment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sections', to='content.sections')),
            ],
            options={
                'verbose_name': 'Assessment Section',
                'verbose_name_plural': 'Assessment Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessment.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='content.question')),
                ('assessment_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.assessmentsection')),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.UniqueConstraint(fields=('assessment', 'section'), name='unique_section_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'question'), name='unique_question_per_assessment'),
        ),
    ]
