# Generated by Django 6.1.1 on 2026-09-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='passing_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What a student must score to pass. Zero means the only bar is scoring nothing at all, which a paper carrying negative marking can still fall below', max_digits=7),
        ),
    ]
