# Generated by Django 6.1.1 on 2026-09-18 05:25

from django.db import migrations, models


def backfill_email_status(apps, schema_editor):
    """Rows written before the field existed only recorded a yes/no. Anything already sent becomes
    Sent, anything carrying an error becomes Failed, and the rest stay Pending."""
    SessionStudent = apps.get_model('session', 'SessionStudent')
    SessionStudent.objects.filter(email_sent=True).update(email_status='Sent')
    SessionStudent.objects.filter(email_sent=False).exclude(email_error='').update(email_status='Failed')


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstudent',
            name='email_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', help_text='Pending until the invite has actually left the mail server', max_length=10),
        ),
        migrations.RunPython(backfill_email_status, migrations.RunPython.noop),
    ]
