# Generated by Django 6.1.1 on 2026-09-18 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('content', '0003_questionhistory'),
        ('session', '0002_sessionstudent_email_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Submitted', 'Submitted')], default='In Progress', max_length=15)),
                ('candidate_image', models.ImageField(help_text='Photo of the student, taken as the test is started', upload_to='candidate/photos/')),
                ('id_proof_image', models.ImageField(help_text='Photo of the identity document, taken as the test is started', upload_to='candidate/id_proofs/')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, help_text='What the student scored across every section', max_digits=9)),
                ('max_marks', models.DecimalField(decimal_places=2, default=0, help_text="The assessment's own total, kept here so an edit to the test later does not rewrite this result", max_digits=9)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('unanswered', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='session.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Attempt',
                'verbose_name_plural': 'Test Attempts',
            },
        ),
        migrations.CreateModel(
            name='TestSectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted')], default='Pending', max_length=10)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Can be below zero where the section carries negative marking', max_digits=9)),
                ('max_marks', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('unanswered', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_attempts', to='assessment.assessmentsection')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='candidate.testattempt')),
            ],
            options={
                'verbose_name': 'Test Section Attempt',
                'verbose_name_plural': 'Test Section Attempts',
                'ordering': ['assessment_section__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, help_text='The question mark when right, the negative mark when wrong and the section carries it, otherwise zero', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessment.assessmentquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='content.questionoption')),
                ('section_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='candidate.testsectionattempt')),
            ],
            options={
                'verbose_name': 'Test Answer',
                'verbose_name_plural': 'Test Answers',
                'ordering': ['assessment_question__order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attempt_per_session_student'),
        ),
        migrations.AddConstraint(
            model_name='testsectionattempt',
            constraint=models.UniqueConstraint(fields=('attempt', 'assessment_section'), name='unique_section_per_attempt'),
        ),
        migrations.AddConstraint(
            model_name='testanswer',
            constraint=models.UniqueConstraint(fields=('section_attempt', 'assessment_question'), name='unique_answer_per_question'),
        ),
    ]
