# Generated by Django 6.1.1 on 2026-09-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='passing_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text="The assessment's pass mark as it stood when the paper was sat, kept here for the same reason", max_digits=9),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The overall score as a share of max_marks, worked out whenever the totals are', max_digits=6),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='result',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Pending', help_text='Pending while the paper is still open, then Pass or Fail against the passing marks above', max_length=10),
        ),
    ]
