# Generated by Django 6.1.1 on 2026-09-17 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_question_questionoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Imported', 'Imported'), ('Updated', 'Updated'), ('Status Changed', 'Status Changed'), ('Deleted', 'Deleted')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('changed_by_email', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_changes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='content.question')),
            ],
            options={
                'verbose_name': 'Question History',
                'verbose_name_plural': 'Question History',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
